ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER SLOTUSER CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER SLOTUSER IDENTIFIED BY SLOTPSW1;
GRANT CONNECT, RESOURCE TO SLOTUSER;
GRANT CREATE TABLE TO SLOTUSER;
GRANT CREATE VIEW TO SLOTUSER;
GRANT CREATE SEQUENCE TO SLOTUSER;
GRANT CREATE PROCEDURE TO SLOTUSER;
GRANT CREATE TRIGGER TO SLOTUSER;
GRANT CREATE TYPE TO SLOTUSER;
GRANT CREATE SYNONYM TO SLOTUSER;
GRANT UNLIMITED TABLESPACE TO SLOTUSER;