version: '3.8'

services:
  slotsbe:
    image: slotsbe:latest   # имя твоего локального образа
    container_name: slotsbe
    ports:
      - "8081:8081"         # проброс порта, если твой Spring Boot слушает 8080
    environment:
      JAVA_OPTS: "-Xms1024m -Xmx1024m"
      # 🗄️ Datasource
      DB_URL: jdbc:oracle:thin:@//localhost:1521/XEPDB1
      DB_USERNAME: SLOTUSER
      DB_PASSWORD: SLOTUSER
      DB_DRIVER: oracle.jdbc.OracleDriver

      # 📧 Email
      MAIL_HOST: smtp.yandex.ru
      MAIL_PORT: 465
      MAIL_USERNAME: tikhonovafZel@yandex.ru
      MAIL_PASSWORD: lrvbtcwgqqmfupgp

    restart: unless-stopped