version: '3.8'

services:
  slotsbe:
    image: slotsbe:latest   # имя твоего локального образа
    container_name: slotsbe
    ports:
      - "8081:8081"         # проброс порта, если твой Spring Boot слушает 8080
    environment:
      JAVA_OPTS: "-Xms1024m -Xmx1024m"
    restart: unless-stopped