accessKey:
  expireDays: ${ACCESS_KEY_EXPIRE_DAYS:31}
debug: false
logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
    root: INFO
slotsbe:
  decodeDate: ${DECODE_DATA:FALSE}
  timeZone: ${TIME_ZONE:Europe/Moscow}

server:
  port: 8081
  servlet:
    session:
      timeout: 64800m
  session:
    timeout: 3888000
spring:
  data:
    rest:
      basePath: /api
      default-page-size: 10
      max-page-size: 10000
      returnBodyOnCreate: true
      returnBodyOnUpdate: true
#  sql:
#    init:
#      mode: always
  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://192.168.222.17:5432/straf}
#    username: ${DATABASE_USER:postgres}
#    password: ${DATABASE_PASSWORD:postgres}
#    url=jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        batch_versioned_data: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  h2:
    console:
      enabled:true
      path:/h2-console
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
    springdoc:
      swagger-ui:
        url: /v3/api-docs
        config-url: /v3/api-docs/swagger-config
