accessKey:
    expireDays: ${ACCESS_KEY_EXPIRE_DAYS:31}
debug: false
logging:
    level:
        org:
            hibernate: INFO
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: INFO
        root: INFO
slotsbe:
    decodeDate: ${DECODE_DATA:FALSE}
    timeZone: ${TIME_ZONE:Europe/Moscow}

server:
    port: 8081
    servlet:
        session:
            timeout: 64800m
    session:
        timeout: 3888000
spring:
    data:
        rest:
            basePath: /api
            default-page-size: 10
            max-page-size: 10000
            returnBodyOnCreate: true
            returnBodyOnUpdate: true
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://192.168.222.17:5432/straf}
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD:postgres}
    jpa:
        hibernate:
            jdbc:
                batch_versioned_data: true
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    batch_size: 20
                order_inserts: true
                order_updates: true
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    servlet:
        multipart:
            max-file-size: 150MB
            max-request-size: 150MB
clickHouse:
    url: //192.168.222.121:8123/slotsbe_logs
interaction:
    redisson:
        server-mode: standalone
        ssl-enable-endpoint-identification: false
        subject-info-ttl-seconds: 60
        subject-rec-ttl-seconds: 60
        address: redis://192.168.222.120:6379
        master-name: mymaster
        auth:
            enabled: false

#springdoc:
#    swagger-ui:
#        configUrl: /v3/api-docs