accessKey:
  expireDays: ${ACCESS_KEY_EXPIRE_DAYS:31}
debug: false
logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
    root: INFO
slotsbe:
  timeZone: ${TIME_ZONE:Europe/Moscow}

server:
  port: 8081
  servlet:
    session:
      timeout: 64800m
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  session:
    timeout: 3888000
spring:
  data:
    rest:
      basePath: /api
      default-page-size: 10
      max-page-size: 10000
      returnBodyOnCreate: true
      returnBodyOnUpdate: true
  #  sql:
  #    init:
  #      mode: always
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//172.26.9.11:1521/mgtoil}
    username: ${DB_USERNAME:AIS_MAIN}
    password: ${DB_PASSWORD:AIS_MAIN}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}
  jpa:
    hibernate:
      ddl-auto: none
    jdbc:
      batch_versioned_data: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
mail:
  smtp:
    host: ${MAIL_SMTP_HOST:smtp.yandex.ru}
    port: ${MAIL_SMTP_PORT:465}
    username: ${MAIL_SMTP_USERNAME:tikhonovafZel@yandex.ru}
    password: ${MAIL_SMTP_PASSWORD:lrvbtcwgqqmfupgp}
    from: ${MAIL_SMTP_FROM:tikhonovafZel@yandex.ru}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            starttls:
              enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  imap:
    host: ${MAIL_IMAP_HOST:imap.yandex.ru}
    port: ${MAIL_IMAP_PORT:993}
    username: ${MAIL_IMAP_USERNAME:tikhonovafZel@yandex.ru}
    password: ${MAIL_IMAP_PASSWORD:lrvbtcwgqqmfupgp}
    protocol: imap
    properties:
      mail:
        store:
          protocol: imap
        imap:
          ssl:
            enable: true

#  mail:
#    host: smtp.yandex.ru
#    port: 465
#    username: tikhonovafZel@yandex.ru
#    password: lrvbtcwgqqmfupgp
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            starttls:
#              enable: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
springdoc:
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: slots-backend
