openapi: "3.0.2"
info:
  title: "slotsbe backend"
  version: "1.01"
servers:
  - url: http://localhost:8081/api
paths:
  /login:
    post:
      summary: Вход в систему
      operationId: login
      tags:
        - LOGIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginDto"
      responses:
        200:
          description: Пустой ответ

  /logout:
    post:
      summary: Выход из системы
      operationId: logout
      tags:
        - LOGIN
      responses:
        200:
          description: Пустой ответ

  /admin/clientUsers:
    post:
      summary: Добавление пользователя
      operationId: addClientUser
      tags:
        - ADMIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/clientUserInDto"
      responses:
        200:
          description: Пустой ответ

  /admin/clientUsers/{id}:
    patch:
      summary: Изменение пользователя
      operationId: modifyClientUser
      tags:
        - ADMIN
      parameters:
        - name: id
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/clientUserInDto"
      responses:
        200:
          description: Пустой ответ

  /session:
    get:
      summary: Выборка данных о сессии пользователя
      operationId: session
      tags:
        - LOGIN
      responses:
        200:
          description: Информация о сессии пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sessionDto"
  /slots/statuses:
    post:
      summary: Выборка списка статусов слотов
      operationId: getSlotStatuses
      tags:
        - SLOT
      responses:
        200:
          description: Список статусов слотов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/slotStatusDtos"
  /slots/search:
    post:
      summary: Выборка списка слотов с фильтром
      operationId: getSlotsByFilters
      tags:
        - SLOT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/slotSearchFilter"
      responses:
        200:
          description: Список слотов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/slotDtos"
  /slots/:
    patch:
      summary: Резервирование слотов
      operationId: reserveSlots
      tags:
        - SLOT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/modifiedSlotDtos"
      responses:
        200:
          description: Пустой ответ
    post:
      summary: формирование слотов на основе шаблона
      operationId: generateSlots
      tags:
        - SLOT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/slotGenerateParams"
      responses:
        200:
          description: Список сообщений о формировании слотов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uploadMessages"

  /slots/download:
    post:
      tags:
        - SLOT
      summary: Выгрузка слотов в Excel файл
      operationId: downloadSlotsToExcel
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/slotSearchFilter"
      responses:
        200:
          description: Excel файл
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /slots/mails:
    patch:
      summary: Отправка писем со слотами пользователям
      operationId: sendMailsToUsers
      tags:
        - SLOT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userIds"
      responses:
        200:
          description: Список сообщений об отправке email
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uploadMessages"
  /slots/template/upload:
    post:
      tags:
        - SLOT
      operationId: slotsTemplateUpload
      summary: Загрузка файла c шаблоном расписания
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Файл для загрузки
      responses:
        200:
          description: Список сообщений о загрузке
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uploadMessages"

  /clients:
    get:
      summary: Выборка списка клиентов
      operationId: getClients
      tags:
        - REF
      responses:
        200:
          description: Список клиентов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/clientDtos"

  /clients/users:
    get:
      summary: Выборка списка пользователей клиентов
      operationId: getClientsUsers
      tags:
        - REF
      responses:
        200:
          description: Список пользователей клиентов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/clientUsersDtos"

  /stores:
    get:
      summary: Выборка списка нефтебаз
      operationId: getStores
      tags:
        - REF
      responses:
        200:
          description: Список нефтебаз
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/storeDtos"
  /loadingPoints/{storeId}:
    get:
      summary: Выборка списка пунктов налива для заданной нефтебазы
      operationId: getLoadingPoints
      tags:
        - REF
      parameters:
        - name: storeId
          description: ИД нефтебазы
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Список пунктов налива
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loadingPointDtos"

components:
  schemas:
    page:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
    paging:
      type: object
      properties:
        number:
          type: integer
          format: int64
          description: Номер выводимой страницы (начинается с 0)
          example: 0
        size:
          type: integer
          format: int64
          description: Количество строк на странице
          example: 20
    sortColumn:
      type: object
      properties:
        columnName:
          type: string
          description: Название столбца (поля)
          example: statusName
        sortDirection:
          type: string
          description: Направление соритрповки (ASC - по возрастаеию,  DESC - по убыванию)
          example: ASC
          default: ASC
    sort:
      type: array
      items:
        $ref: "#/components/schemas/sortColumn"

    loginDto:
      type: object
      description: Данные для входа в систему
      properties:
        username:
          type: string
          description: Имя пользователя
          example: USER1
        password:
          type: string
          description: Наименование
          example: Наименование 1

    slotDtos:
      type: array
      description: Список слотов
      items:
        $ref: "#/components/schemas/slotDto"
    slotDto:
      type: object
      description: Слот
      properties:
        nSlotId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        dDate:
          type: string
          format: date
          description: Дата слота
          example: 2025-07-12
        dStartTime:
          type: string
          description: Время начала слота
          format: time
          example: 14:30:00
        dEndTime:
          type: string
          format: time
          description: Время окончания слота
          example: 14:30:00
        nLoadingPointId:
          type: integer
          format: int64
          description: Идентификатор пункта отпуска
          example: 1
        vcLoadingPointCode:
          type: string
          description: Код пункта отпуска
          example: Код 1
        vcLoadingPointName:
          type: string
          description: Наименование пункта отпуска
          example: Наименование 1
        vcLoadingPointComment:
          type: string
          description: Комментарий
          example: Комментарий 1
        nStoreId:
          type: integer
          format: int64
          description: Идентификатор нефтебазы
          example: 1
        vcStoreCode:
          type: string
          description: Код нефтебазы
          example: Код 1
        vcStoreName:
          type: string
          description: Наименование нефтебазы
          example: Наименование 1
        nClientId:
          type: integer
          format: int64
          description: Идентификатор клиента
          example: 1
        vcClientCode:
          type: string
          description: Код клиента
          example: Код 1
        vcClientName:
          type: string
          description: Наименование клиента
          example: Наименование 1
        nStatusId:
          type: integer
          format: int64
          description: Идентификатор статуса слота
          example: 1
        vcStatusCode:
          type: string
          description: Код статуса слота
          example: Код 1
        vcStatusName:
          type: string
          description: Наименование статуса слота
          example: Наименование 1

    modifiedSlotDtos:
      type: array
      description: Список изменений слотов
      items:
        $ref: "#/components/schemas/modifiedSlotDto"
    modifiedSlotDto:
      type: object
      description: Изменение слота
      properties:
        nSlotId:
          type: integer
          format: int64
          description: Идентификатор слота
          example: 1
        nClientId:
          type: integer
          format: int64
          description: Идентификатор клиента
          example: 1
        nStatusId:
          type: integer
          format: int64
          description: Идентификатор статуса
          example: 1
    clientDtos:
      type: array
      description: Список клиентов
      items:
        $ref: "#/components/schemas/clientDto"
    clientDto:
      type: object
      description: Клиент
      properties:
        nClientId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        vcCode:
          type: string
          description: код
          example: Код 1
        vcName:
          type: string
          description: Наименование
          example: Наименование 1
    clientUsersDtos:
      type: array
      description: Список пользователей клиентов
      items:
        $ref: "#/components/schemas/clientUsersDto"
    clientUsersDto:
      type: object
      description: Пользователь клиента
      properties:
        nUserId:
          type: integer
          format: int64
          description: Идентификатор пользователя клиента
          example: 1
        vcInfo:
          type: string
          description: Наименование клиента + email
          example: Наименование 1
        vcEmail:
          type: string
          description: email
          example: example@mail.ru

    storeDtos:
      type: array
      description: Список нефтебаз
      items:
        $ref: "#/components/schemas/storeDto"
    storeDto:
      type: object
      description: Нефтебаза
      properties:
        nStoreId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        vcCode:
          type: string
          description: код
          example: Код 1
        vcName:
          type: string
          description: Наименование
          example: Наименование 1


    loadingPointDtos:
      type: array
      description: Список пунктов налива
      items:
        $ref: "#/components/schemas/loadingPointDto"
    loadingPointDto:
      type: object
      description: Пункт налива
      properties:
        nLoadingPointId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        nStoreId:
          type: integer
          format: int64
          description: Идентификатор нефтебазы
          example: 1
        vcStoreName:
          type: string
          description: Наименование нефтебазы
          example: Наименование нефтебазы 1
        vcCode:
          type: string
          description: Код
          example: Код 1
        vcName:
          type: string
          description: Наименование
          example: Наименование 1
        vcComment:
          type: string
          description: Комментарий
          example: Комментарий 1

    slotSearchDto:
      type: object
      description: Параметры выборки списка слотов
      properties:
        slotSearchFilter:
          $ref: "#/components/schemas/slotSearchFilter"
    slotSearchFilter:
      description: Фильтр для выборки списка слотов
      type: object
      properties:
        nStoreIds:
          description: Список идентификаторов нефтебаз
          type: array
          items:
            type: integer
            format: int64
        nClientIds:
          description: Список иентификаторов клиента
          type: array
          items:
            type: integer
            format: int64
        dDateBegin:
          type: string
          format: date
          description: Дата слота
          example: 2025-07-12
        dDateEnd:
          type: string
          format: date
          description: Дата слота
          example: 2025-07-12
        nStatusId:
          type: integer
          format: int64
          description: Идентификатор статуса слота
          example: 1
    slotGenerateParams:
      description: Параметры для генерации слотов
      type: object
      properties:
        nStoreIds:
          description: Список идентификаторов нефтебаз
          type: array
          items:
            type: integer
            format: int64
        dDateBegin:
          type: string
          format: date
          description: Дата начала слотов
          example: 2025-07-12
        dDateEnd:
          type: string
          format: date
          description: Дата окончания слота
          example: 2025-07-19
    userIds:
      description: Список идентификаторов пользователей
      type: array
      items:
        type: integer
        format: int64
    uploadMessages:
      description: Список сообщений о загрузке
      type: array
      items:
        type: string
        description: сообщение о загрузке
    
    slotStatusDtos:
      type: array
      description: Список статусов слотов
      items:
        $ref: "#/components/schemas/slotStatusDto"
    slotStatusDto:
      type: object
      description: Статус слота
      properties:
        nStatusId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        vcCode:
          type: string
          description: код
          example: Код 1
        vcName:
          type: string
          description: Наименование
          example: Наименование 1
    sessionDto:
      type: object
      description: Данные о сессии пользователя
      properties:
        actual:
          type: boolean
          description: Признак актуальности сессии
          example: true
        username:
          type: string
          description: Имя пользователя
          example: USER1
        name:
          type: string
          description: Наименование пользователя
          example: Пользователь-1
        roleId:
          type: integer
          format: int64
          description: Идентификатор роли пользователя
          example: ADMIN
        role:
          type: string
          description: Роль пользователя
          example: ADMIN
    clientUserInDto:
      type: object
      description: Данные о пользователе
      properties:
        vcFirstName:
          type: string
          description: Имя
          example: Петр
        vcLastName:
          type: string
          description: Фамилия
          example: Петров
        vcSecondName:
          type: string
          description: Отчество
          example: Петрович
        vcEmail:
          type: string
          description: email
          example: email
        dStartDate:
          type: string
          format: date
          description: Дата начала действия
          example: 2021-08-17
        dEndDate:
          type: string
          format: date
          description: Дата окончания действия
          example: 2021-08-17
        nRoleId:
          type: integer
          format: int64
          description: Идентификатор роли
          example: 1
        vcClientCode:
          type: string
          description: Код клиента
          example: Код 1
        vcPhone:
          type: string
          description: phone
          example: +7(916)234-67-89
        vcLogin:
          type: string
          description: Логин
          example: test
        vcPassword:
          type: string
          description: Логин
          example: test

