openapi: "3.0.2"
info:
  title: "slotsbe backend"
  version: "1.01"
servers:
  - url: http://localhost:8085/api
paths:
  /login:
    post:
      summary: Вход в систему
      operationId: login
      tags:
        - LOGIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginDto"
      responses:
        200:
          description: Пустой ответ

  /logout:
    post:
      summary: Выход из системы
      operationId: logout
      tags:
        - LOGIN
      responses:
        200:
          description: Пустой ответ

  /slots:
    post:
      summary: Выборка списка слотов
      operationId: getSlots
      tags:
        - SLOT
      responses:
        200:
          description: Список слотов с фильтром
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/slotDtos"
    patch:
      summary: Редактирование слотов
      operationId: modifySlots
      tags:
        - SLOT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/modifiedSlotDtos"
      responses:
        200:
          description: Список слотов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/slotDtos"

components:
  schemas:
    page:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
    paging:
      type: object
      properties:
        number:
          type: integer
          format: int64
          description: Номер выводимой страницы (начинается с 0)
          example: 0
        size:
          type: integer
          format: int64
          description: Количество строк на странице
          example: 20
    sortColumn:
      type: object
      properties:
        columnName:
          type: string
          description: Название столбца (поля)
          example: statusName
        sortDirection:
          type: string
          description: Направление соритрповки (ASC - по возрастаеию,  DESC - по убыванию)
          example: ASC
          default: ASC
    sort:
      type: array
      items:
        $ref: "#/components/schemas/sortColumn"

    loginDto:
      type: object
      description: Данные для входа в систему
      properties:
        username:
          type: string
          description: Имя пользователя
          example: USER1
        password:
          type: string
          description: Наименование
          example: Наименование 1
    slotDtos:
      type: array
      description: Список слотов
      items:
        $ref: "#/components/schemas/slotDto"
    slotDto:
      type: object
      description: Слот
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        name:
          type: string
          description: Наименование
          example: Наименование 1
        description:
          type: string
          description: Описание
          example: Описание 1
    modifiedSlotDtos:
      type: array
      description: Список изменений слотов
      items:
        $ref: "#/components/schemas/modifiedSlotDto"
    modifiedSlotDto:
      type: object
      description: Изменение слота
      properties:
        slotId:
          type: integer
          format: int64
          description: Идентификатор слота
          example: 1
        status:
          type: integer
          format: int64
          description: 0 - свободен,  1- занято
          example: 1

