openapi: "3.0.2"
info:
  title: "slotsbe backend"
  version: "1.01"
servers:
  - url: http://localhost:8085/api
paths:
  /login:
    post:
      summary: Вход в систему
      operationId: login
      tags:
        - LOGIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginDto"
      responses:
        200:
          description: Пустой ответ

  /logout:
    post:
      summary: Выход из системы
      operationId: logout
      tags:
        - LOGIN
      responses:
        200:
          description: Пустой ответ

  /slots/search:
    post:
      summary: Выборка списка слотов с фильтром
      operationId: getSlotsByFilters
      tags:
        - SLOT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/slotSearchFilter"
      responses:
        200:
          description: Список слотов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/slotDtos"
  /slots/:
    patch:
      summary: Резервирование слотов
      operationId: reserveSlots
      tags:
        - SLOT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/modifiedSlotDtos"
      responses:
        200:
          description: Пустой ответ

  /slots/download:
    post:
      tags:
        - SLOT
      summary: Выгрузка слотов в Excel файл
      operationId: downloadSlotsToExcel
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/slotSearchFilter"
      responses:
        200:
          description: Excel файл
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /clients:
    get:
      summary: Выборка списка клиентов
      operationId: getСlients
      tags:
        - REF
      responses:
        200:
          description: Список клиентов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/clientDtos"

  /stores:
    get:
      summary: Выборка списка нефтебаз
      operationId: getStores
      tags:
        - REF
      responses:
        200:
          description: Список нефтебаз
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/storeDtos"

  /loadingPoints:
    get:
      summary: Выборка списка пунктов налива
      operationId: getLoadingPoints
      tags:
        - REF
      responses:
        200:
          description: Список пунктов налива
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loadingPointDtos"

components:
  schemas:
    page:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
    paging:
      type: object
      properties:
        number:
          type: integer
          format: int64
          description: Номер выводимой страницы (начинается с 0)
          example: 0
        size:
          type: integer
          format: int64
          description: Количество строк на странице
          example: 20
    sortColumn:
      type: object
      properties:
        columnName:
          type: string
          description: Название столбца (поля)
          example: statusName
        sortDirection:
          type: string
          description: Направление соритрповки (ASC - по возрастаеию,  DESC - по убыванию)
          example: ASC
          default: ASC
    sort:
      type: array
      items:
        $ref: "#/components/schemas/sortColumn"

    loginDto:
      type: object
      description: Данные для входа в систему
      properties:
        username:
          type: string
          description: Имя пользователя
          example: USER1
        password:
          type: string
          description: Наименование
          example: Наименование 1

#    slotSearchResultDto:
#      description: Список слотов
#      type: object
#      properties:
#        slotDtos:
#          type: array
#          items:
#            $ref: "#/components/schemas/slotDto"
#        page:
#          $ref: "#/components/schemas/page"

    slotDtos:
      type: array
      description: Список слотов
      items:
        $ref: "#/components/schemas/slotDto"
    slotDto:
      type: object
      description: Слот
      properties:
        nSlotId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        dDate:
          type: string
          format: date
          description: Дата слота
          example: 2025-07-12
        dStartTime:
          type: string
          description: Время начала слота
          format: time
          example: 14:30:00
        dEndTime:
          type: string
          format: time
          description: Время окончания слота
          example: 14:30:00
        nLoadingPointId:
          type: integer
          format: int64
          description: Идентификатор пункта отпуска
          example: 1
        vcLoadingPointCode:
          type: string
          description: Код пункта отпуска
          example: Код 1
        vcLoadingPointName:
          type: string
          description: Наименование пункта отпуска
          example: Наименование 1
        vcLoadingPointComment:
          type: string
          description: Комментарий
          example: Комментарий 1
        nStoreId:
          type: integer
          format: int64
          description: Идентификатор нефтебазы
          example: 1
        vcStoreCode:
          type: string
          description: Код нефтебазы
          example: Код 1
        vcStoreName:
          type: string
          description: Наименование нефтебазы
          example: Наименование 1
        nClientId:
          type: integer
          format: int64
          description: Идентификатор клиента
          example: 1
        vcClientCode:
          type: string
          description: Код клиента
          example: Код 1
        vcClientName:
          type: string
          description: Наименование клиента
          example: Наименование 1
        vcStatus:
          type: string
          description: Статус (F - free, B - busy)
          example: B

    modifiedSlotDtos:
      type: array
      description: Список изменений слотов
      items:
        $ref: "#/components/schemas/modifiedSlotDto"
    modifiedSlotDto:
      type: object
      description: Изменение слота
      properties:
        nSlotId:
          type: integer
          format: int64
          description: Идентификатор слота
          example: 1
        nClientId:
          type: integer
          format: int64
          description: Идентификатор клиента
          example: 1
        vcStatus:
          type: string
          description: Статус (F - free, B - busy)
          example: B
    clientDtos:
      type: array
      description: Список клиентов
      items:
        $ref: "#/components/schemas/clientDto"
    clientDto:
      type: object
      description: Клиент
      properties:
        nClientId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        vcCode:
          type: string
          description: код
          example: Код 1
        vcName:
          type: string
          description: Наименование
          example: Наименование 1
    storeDtos:
      type: array
      description: Список нефтебаз
      items:
        $ref: "#/components/schemas/storeDto"
    storeDto:
      type: object
      description: Нефтебаза
      properties:
        nStoreId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        vcCode:
          type: string
          description: код
          example: Код 1
        vcName:
          type: string
          description: Наименование
          example: Наименование 1


    loadingPointDtos:
      type: array
      description: Список пунктов налива
      items:
        $ref: "#/components/schemas/loadingPointDto"
    loadingPointDto:
      type: object
      description: Пункт налива
      properties:
        nLoadingPointId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        nStoreId:
          type: integer
          format: int64
          description: Идентификатор нефтебазы
          example: 1
        vcStoreName:
          type: string
          description: Наименование нефтебазы
          example: Наименование нефтебазы 1
        vcCode:
          type: string
          description: Код
          example: Код 1
        vcName:
          type: string
          description: Наименование
          example: Наименование 1
        vcComment:
          type: string
          description: Комментарий
          example: Комментарий 1

    slotSearchDto:
      type: object
      description: Параметры выборки списка слотов
      properties:
        slotSearchFilter:
          $ref: "#/components/schemas/slotSearchFilter"
    slotSearchFilter:
      description: Фильтр для выборки списка слотов
      type: object
      properties:
        nStoreId:
          type: integer
          format: int64
          description: Идентификатор нефтебазы
          example: 1
        nClientId:
          type: integer
          format: int64
          description: Идентификатор клиента
          example: 1
        dDate:
          type: string
          format: date
          description: Дата слота
          example: 2025-07-12
        vcStatus:
          type: string
          description: Статус
          example: B
